name: Build awslogin
on:
  release:
    types: [created]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Compile
      run: make all
    - name: Artifact-ify it
      uses: actions/upload-artifact@v1
      with:
        name: awslogin
        path: awslogin*
